name: Teste Auth Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v2

      - name: Configurar Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Instalar dependencias
        work-directory: ./burguer-app/auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: | 
          pytest -v